spring.application.name=agencia-viagem-ai

langchain4j.ollama.base-url=http://localhost:11434
langchain4j.ollama.chat-model=phi4-mini
langchain4j.ollama.embedding-model=nomic-embed-text
langchain4j.ollama.timeout-seconds=180

rag.documents.path=src/main/resources/rag/pacotes-viagem.md
rag.splitter.max-segment-size=200
rag.splitter.max-overlap-size=20

# Used with PgVector
langchain4j.pgvector.host=localhost
langchain4j.pgvector.port=5432
langchain4j.pgvector.database=agencia_viagem
langchain4j.pgvector.user=postgres
langchain4j.pgvector.password=postgres
langchain4j.pgvector.dimension=768
langchain4j.pgvector.table=travel_embeddings
langchain4j.pgvector.drop-table-first=true