spring.application.name=project-spring-mvc-events

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:mem:db_events
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true